### ISSUE TITLE
After :PlugInstall it shows beacon floating window that doesnt fade away 

### ISSUE THREAD

**Issue by genesistms** [DanilaMihailov/beacon.nvim#1]
Whenever i run :PlugInstall it creates beacon window on top and it wont disappear.

![beacon_bug](https://user-images.githubusercontent.com/19390954/85693687-c013c880-b6d6-11ea-901a-3126f068c4ff.png)

```
NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/builddir/build/BUILD/neovim-0.4.3.0.git.14117.30b02a1be/build/config -I/builddir/build/BUILD/neovim-0.4.3.0.git.14117.30b02a1be/src -I/usr/include -I/usr/include/lua-5.1 -I/builddir/build/BUILD/neovim-0.4.3.0.git.14117.30b02a1be/build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.4.3.0.git.14117.30b02a1be/build/include
Compiled by mockbuild
```

**Comment by DanilaMihailov** [comment]
Yeah, I see the same, but in the bottom for me. Will look in to it. For now you can fix it by ignoring this buffer, try
```viml
let g:beacon_ignore_buffers = ["[Plugins]"]
```

Thank you for feedback :)

**Comment by DanilaMihailov** [comment]
Fixed in new release. Problem was - plugin loaded multiple times. 

If problem persists please let me now :)

**Comment by genesistms** [comment]
> Yeah, I see the same, but in the bottom for me. Will look in to it. For now you can fix it by ignoring this buffer, try
> 
> ```viml
> let g:beacon_ignore_buffers = ["[Plugins]"]
> ```
> 
> Thank you for feedback :)

When i try this it ignores every buffer i open.

**Comment by genesistms** [comment]
> Fixed in new release. Problem was - plugin loaded multiple times.
> 
> If problem persists please let me now :)

It is working. Thanks for quick fix - so far i like the plugin.

**Comment by DanilaMihailov** [comment]
> When i try this it ignores every buffer i open.

I will look in to it, code looks fine, I guess regex is not right. Vim regexes are kinda wierd)

> It is working. Thanks for quick fix - so far i like the plugin.

Glad to hear :)
