### ISSUE TITLE
Change of Color does not work

### ISSUE THREAD

**Issue by centuryx476** [DanilaMihailov/beacon.nvim#31]
No matter what color I change it too. It stays white.
This is a pretty simple setup I have.
LazyVim config, I put the beacon.lua config in its own file and load it in the init.lua

![image](https://github.com/user-attachments/assets/e750a3a5-75be-45b7-bc62-08b3443d8b18)

**Comment by csessh** [comment]
That config doesn't look right @centuryx476 

Try this if you haven't:

```
return {
    "DanilaMihailov/beacon.nvim",
    opts = {
        enabled = true,
        speed = 2,
        width = 40,
        winblend = 70,
        fps = 60,
        min_jump = 10,
        cursor_events = {"CursorMoved"},
        window_events = { "WinEnter", "FocusGained" },
        highlight = { bg = "green", ctermbg = 15 },
    },
}
```

**Comment by centuryx476** [comment]
Thank you, 
That did the trick...
