### ISSUE TITLE
Animation played when moving over folds

### ISSUE THREAD

**Issue by gbcreation** [DanilaMihailov/beacon.nvim#4]
First, thank you very much for this very useful plugin.

I noticed that if the cursor is moved over a fold, the jump animation is played.
Would it be possible to detect moving over folds and not play the animation in
that case?

**Comment by DanilaMihailov** [comment]
Sure, I think it is possible to detect folds, will look into it tomorrow. I will tell you, when release with fixes comes out.

Thanks for feedback :)

**Comment by DanilaMihailov** [comment]
Fixed in a new release. Let me know if problem persists :)

**Comment by gbcreation** [comment]
It works flawlessly! Thank you very much :+1:
