### ISSUE TITLE
Moving cursor over a fold triggers beacon

### ISSUE THREAD

**Issue by shaahiiin** [DanilaMihailov/beacon.nvim#8]
It looks like beacon gets triggered when you move the cursor over a fold (of length more than `g:beacon_minimal_jump`) with j/k

**Comment by shaahiiin** [comment]
Sorry, did not see #5 
Updating the plugin fixed this.
Thank you very much. This plugin is very useful :)

**Comment by DanilaMihailov** [comment]
No problem, glad it works for you :)
